routes/web.php
       Route::post('admin/question-category/updateStatus', 'admin\QuestionCategoryController@updateStatus');
       Route::resource('admin/question-category', 'admin\QuestionCategoryController');
   
       //QUestion Category Routings ends

       //Question Routings

       Route::post('admin/question/updateSortorder', 'admin\QuestionController@updateSortorder');
       Route::post('admin/question/destroyAll', 'admin\QuestionController@destroyAll');
       Route::post('admin/question/updateStatus', 'admin\QuestionController@updateStatus');
       Route::resource('admin/question', 'admin\QuestionController');
   
       //QUestion Routings ends

       

        Route::get('admin/plan/topic/{programId}/{subjectId}', ['as' => 'plan.topic', 'uses' => 'admin\PlanController@topic']);
    
        Route::post('admin/plan/delete/{id}', ['as' => 'plan.delete', 'uses' => 'admin\PlanController@delete']);
    
        Route::resource('admin/plan', 'admin\PlanController');
    
       //Testimonial Routings
    
       Route::post('admin/testimonial/updateSortorder', 'admin\TestimonialController@updateSortorder');
       Route::post('admin/testimonial/destroyAll', 'admin\TestimonialController@destroyAll');
       Route::post('admin/testimonial/updateStatus', 'admin\TestimonialController@updateStatus');
       Route::resource('admin/testimonial', 'admin\TestimonialController');
    
       //Testimonial Routings ends
    
    
        //Program Routings
    
        Route::post('admin/program/updateSortorder', 'admin\ProgramController@updateSortorder');
        Route::post('admin/program/destroyAll', 'admin\ProgramController@destroyAll');
        Route::post('admin/program/updateStatus', 'admin\ProgramController@updateStatus');
        Route::resource('admin/program', 'admin\ProgramController');
    
        //Program Routings ends
    
        //Page Routings
    
        Route::post('admin/page/updateSortorder', 'admin\PageController@updateSortorder');
        Route::post('admin/page/destroyAll', 'admin\PageController@destroyAll');
        Route::post('admin/page/updateStatus', 'admin\PageController@updateStatus');
        Route::resource('admin/page', 'admin\PageController');
    
        //Page Routings ends
    
          //Subject Routings
          Route::post('admin/subject/getSubjectByProgramId', 'admin\SubjectController@getSubjectByProgramId');
          Route::post('admin/subject/updateSortorder', 'admin\SubjectController@updateSortorder');
          Route::post('admin/subject/destroyAll', 'admin\SubjectController@destroyAll');
          Route::post('admin/subject/updateStatus', 'admin\SubjectController@updateStatus');
          Route::resource('admin/subject', 'admin\SubjectController');
      
          //Program Routings ends
    
        //Subscription Routings
    
         Route::post('admin/subscription/updateSortorder', 'admin\SubscriptionController@updateSortorder');
         Route::post('admin/subscription/destroyAll', 'admin\SubscriptionController@destroyAll');
         Route::post('admin/subscription/updateStatus', 'admin\SubscriptionController@updateStatus');
         Route::resource('admin/subscription', 'admin\SubscriptionController');
     
        //Subscription Routings ends
    
        //Subscription Member Routings
    
         Route::post('admin/subscription-member/updateSortorder', 'admin\SubscriptionMemberController@updateSortorder');
         Route::post('admin/subscription-member/destroyAll', 'admin\SubscriptionMemberController@destroyAll');
         Route::post('admin/subscription-member/updateStatus', 'admin\SubscriptionMemberController@updateStatus');
         Route::resource('admin/subscription-member', 'admin\SubscriptionMemberController');
     
         //Subscription Member Routings ends
    
           
    
        //meeting techer scheduling Routings
    
        //  Route::post('admin/meeting-teacher-scheduling/updateSortorder', 'admin\MeetingTeacherSchedulingController@updateSortorder');
        //  Route::post('admin/meeting-teacher-scheduling/destroyAll', 'admin\MeetingTeacherSchedulingController@destroyAll');
        //  Route::post('admin/meeting-teacher-scheduling/updateStatus', 'admin\MeetingTeacherSchedulingController@updateStatus');
        //  Route::resource('admin/meeting-teacher-scheduling', 'admin\MeetingTeacherSchedulingController');
     
         //meeting techer scheduling Routings ends
    
        //teacher class Routings
    
        Route::post('admin/teacher-class/updateSortorder', 'admin\TeacherClassController@updateSortorder');
        Route::post('admin/teacher-class/destroyAll', 'admin\TeacherClassController@destroyAll');
        Route::post('admin/teacher-class/updateStatus', 'admin\TeacherClassController@updateStatus');
        Route::resource('admin/teacher-class', 'admin\TeacherClassController');
        Route::post('admin/studentList', 'admin\TeacherClassController@studentList');
     
         //teacher class Routings ends
    
         //Blog Routings
    
         Route::post('admin/blog/updateSortorder', 'admin\BlogController@updateSortorder');
         Route::post('admin/blog/destroyAll', 'admin\BlogController@destroyAll');
         Route::post('admin/blog/updateStatus', 'admin\BlogController@updateStatus');
         Route::resource('admin/blog', 'admin\BlogController');
     
         //Blog Routings ends
    
        //Banner Routings
    
         Route::post('admin/banner/updateSortorder', 'admin\BannerController@updateSortorder');
         Route::post('admin/banner/destroyAll', 'admin\BannerController@destroyAll');
         Route::post('admin/banner/updateStatus', 'admin\BannerController@updateStatus');
         Route::resource('admin/banner', 'admin\BannerController');
     
         //Banner Routings ends
    
    
         //Contact Routings
    
         Route::post('admin/contact/updateSortorder', 'admin\ContactController@updateSortorder');
         Route::post('admin/contact/destroyAll', 'admin\ContactController@destroyAll');
         Route::post('admin/contact/updateStatus', 'admin\ContactController@updateStatus');
         Route::resource('admin/contact', 'admin\ContactController');
     
         //Contact Routings ends
    
         //Blog Routings
    
         Route::post('admin/user/updateSortorder', 'admin\UserController@updateSortorder');
         Route::post('admin/user/destroyAll', 'admin\UserController@destroyAll');
         Route::post('admin/user/updateStatus', 'admin\UserController@updateStatus');
         Route::resource('admin/user', 'admin\UserController');
     
         //Blog Routings ends
    
        //Master/States Routings
    
         Route::post('admin/state/updateSortorder', 'admin\StatesController@updateSortorder');
         Route::post('admin/state/destroyAll', 'admin\StatesController@destroyAll');
         Route::post('admin/state/updateStatus', 'admin\StatesController@updateStatus');
         Route::resource('admin/state', 'admin\StatesController');
     
         //Master/States Routings ends
    
        //Master/Time-Slot Routings
    
         Route::post('admin/time-slot/updateSortorder', 'admin\TimeSlotController@updateSortorder');
         Route::post('admin/time-slot/destroyAll', 'admin\TimeSlotController@destroyAll');
         Route::post('admin/time-slot/updateStatus', 'admin\TimeSlotController@updateStatus');
         Route::resource('admin/time-slot', 'admin\TimeSlotController');
     
         //Master/Time-Slot  Routings ends
    
        //Topic Routings
         
         Route::post('admin/topic/updateSortorder', 'admin\TopicController@updateSortorder');
         Route::post('admin/topic/destroyAll', 'admin\TopicController@destroyAll');
         Route::post('admin/topic/updateStatus', 'admin\TopicController@updateStatus');
         Route::resource('admin/topic', 'admin\TopicController');
     
         //Topic Routings ends
    
           //Order Routings
    
        Route::post('admin/order/updateSortorder', 'admin\OrderController@updateSortorder');
        Route::post('admin/order/destroyAll', 'admin\OrderController@destroyAll');
        Route::post('admin/order/updateStatus', 'admin\OrderController@updateStatus');
        Route::resource('admin/order', 'admin\OrderController');
    
        //Order Routings endss





    });    

    /*

    //-------Console Product Routing---------//

    //Route for passing multiple parameters
    //View Syntax {route('prom.edit',['id' => $value->id,'catId' => 1])}}
    //------
    //Route::get('admin/promoter/edit/{id}/{catId}', ['as' => 'prom.edit', 'uses' => 'admin\PromoterController@edit']);
    Route::post('admin/product/updateSortorder', 'admin\ProductController@updateSortorder');
    Route::post('admin/product/destroyAll', 'admin\ProductController@destroyAll');
    Route::post('admin/product/updateStatus', 'admin\ProductController@updateStatus');
    Route::get('/admin/product/dimension/{productId}', 'admin\ProductController@dimension');
    Route::resource('admin/product', 'admin\ProductController');

    //Product Dimension Routings

    Route::get('admin/product-dimension/{productId}/', ['as' => 'productDimension.index', 'uses' => 'admin\ProductDimensionController@index']);
    Route::get('admin/product-dimension/create/{productId}/', ['as' => 'productDimension.create', 'uses' => 'admin\ProductDimensionController@create']);
    Route::get('admin/product-dimension/edit/{id}/{productId}/', ['as' => 'productDimension.edit', 'uses' => 'admin\ProductDimensionController@edit']);
    Route::post('admin/product-dimension/store/', ['as' => 'productDimension.store', 'uses' => 'admin\ProductDimensionController@store']);
    Route::put('admin/product-dimension/update/', ['as' => 'productDimension.update', 'uses' => 'admin\ProductDimensionController@update']);
    Route::delete('admin/product-dimension/destroy/', ['as' => 'productDimension.delete', 'uses' => 'admin\ProductDimensionController@destroy']);

app/Http/Controllers/admin/SubscriptionMemberController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Admin\SubscriptionMember;
use Illuminate\Support\Facades\Auth;
use App\Model\Admin\User;
use App\Model\Admin\Role;
use App\Model\Admin\Subscription;



class SubscriptionMemberController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware(function ($request, $next) {
            $this->userId = Auth::user()->id;
            $this->accountId = Auth::user()->accountId;
            return $next($request);
        });
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = array();

        $data["subscriptionMember"] = SubscriptionMember::orderBy('sortOrder')->get();
      

        $data["pageTitle"] = 'Manage Subscription Member';
        $data["activeMenu"] = 'subscription-member';
        return view('admin.subscriptionMember.manage')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $data = array();

        $data["role"] = Role::whereIn('id', [3, 4])->get();
        $data["subscriptionId"] = Subscription::orderBy('id')->get();

        $data["pageTitle"] = 'Add Subscription Member';
        $data["activeMenu"] = 'subscription-member';
        return view('admin.subscriptionMember.create')->with($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate(request(), [
            'userId' => 'required',
            'subscriptionId' => 'required',
        ]);

        $subscriptionMember = new SubscriptionMember();

        $days = Subscription::orderBy('sortOrder')->get();
        foreach ($days as $key => $value) {

        $date =date("Y-m-d");
        $day = $value->days;
        $expiryDate=date('Y-m-d', strtotime("+$day days"));
        }

        $subscriptionMember->userId = $request->input('userId');
        $subscriptionMember->subscriptionId = $request->input('subscriptionId');
        $subscriptionMember->expiryDate = $expiryDate;
       
        $subscriptionMember->status = 1;
        $subscriptionMember->sortOrder = 1;

        $subscriptionMember->increment('sortOrder');

        $subscriptionMember->save();

        return redirect()->route('subscription-member.index')->with('message', 'Subscription Member Added Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
        $data = array();
        
        $data['user'] = SubscriptionMember::find($id);
        $data["role"] = Role::whereIn('id', [3, 4])->get();

        $data['subscription'] = SubscriptionMember::find($id);
        $data["subscriptionId"] = Subscription::orderBy('id')->get();

        $data['subscriptionMember'] = SubscriptionMember::find($id);

        $data["editStatus"] = 1;
        $data["pageTitle"] = 'Update Subscription Member';
        $data["activeMenu"] = 'subscription-mmber';
        return view('admin.subscriptionMember.create')->with($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {

        $this->validate(request(), [
            'userId' => 'required',
            'subscriptionId' => 'required',
        ]);
        
        $id = $request->input('id');

        $subscriptionMember = SubscriptionMember::find($id);

        $subscriptionMember = new SubscriptionMember();

        $days = Subscription::orderBy('sortOrder')->get();
        foreach ($days as $key => $value) {

        $date =date("Y-m-d");
        $day = $value->days;
        $expiryDate=date('Y-m-d', strtotime("+$day days"));
        }


    $subscriptionMember->userId = $request->input('userId');
    $subscriptionMember->subscriptionId = $request->input('subscriptionId');

        $subscriptionMember->save();

        return redirect()->route('subscription-member.index')->with('message', 'Subscription Member Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        $id = $request->id;
        $subscriptionMember = SubscriptionMember::find($id);
        $subscriptionMember->delete($id);

        return response()->json([
            'status' => 1,
            'message' => 'Delete Successfull',
            'response' => $request->id
        ]);
    }

    /**
     * Remove all selected resource from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function destroyAll(Request $request)
    {

        $record = $request->input('deleterecords');

        if (isset($record) && !empty($record)) {

            foreach ($record as $id) {
                $subscriptionMember = SubscriptionMember::find($id);
                $subscriptionMember->delete();
            }
        }

        return response()->json([
            'status' => 1,
            'message' => 'Delete Successfull',
            'response' => ''
        ]);
    }

    /**
     * Update SortOrder.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function updateSortorder(Request $request)
    {
        $data = $request->records;
        $decoded_data = json_decode($data);
        $result = 0;

        if (is_array($decoded_data)) {
            foreach ($decoded_data as $values) {

                $id = $values->id;
                $subscriptionMember = SubscriptionMember::find($id);
                $subscriptionMember->sortOrder = $values->position;
                $result = $subscriptionMember->save();
            }
        }

        if ($result) {
            $response = array('status' => 1, 'message' => 'Sort order updated', 'response' => $data);
        } else {
            $response = array('status' => 0, 'message' => 'Something went wrong', 'response' => $data);
        }

        return response()->json($response);
    }

    /**
     * Update Status resource from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function updateStatus(Request $request)
    {
        $status = $request->status;
        $id = $request->id;

        $subscriptionMember = SubscriptionMember::find($id);
        $subscriptionMember->status = $status;
        $result = $subscriptionMember->save();

        if ($result) {
            $response = array('status' => 1, 'message' => 'Status updated', 'response' => '');
        } else {
            $response = array('status' => 0, 'message' => 'Something went wrong', 'response' => '');
        }

        return response()->json($response);
    }

}

resources/views/admin/subscriptionMember/create.blade.php
@extends('layout.admin')
@section('content')

<div class="row">


    <div class="col-lg-12 col-ml-12">
        <div class="row">
            <!-- basic form start -->

            <div class="col-12 mt-5 start-form-sec">

                <div class="card">
                    <div class="card-body">

                        <!-- <h4 class="header-title">Basic form</h4> -->

                        <form id="subscriptionMemberForm" method="post" action="@if(isset($editStatus)){{ route('subscription-member.update', $subscriptionMember->id) }} @else {{ route('subscription-member.store')}}@endif" enctype='multipart/form-data'>

                            {{ csrf_field() }}

                            @if(isset($editStatus))
                            @method('PUT')
                            @endif


                            @if(session()->has('message'))
                            <div class="alert alert-danger">
                                {{ session()->get('message') }}
                            </div>
                            @endif


                            @foreach($errors->all() as $error)
                            <li>{{$error}}</li>
                            @endforeach

                            <div class="row">

                                <div class="col-6 mt-5">
                                    <div class="form-group">
                                    <div class="form-group">
                                        <label for="userId">User</label>
                                        <select class="form-control selectpicker" id="userId" name="userId" data-live-search="true">
                                            <option value="">Select User</option>
                                            @if(isset($role))
                                            @foreach($role as $value)
                                            <option value="{{$value->id}}" @if (old('roleId', isset($user->userId) ? $user->userId : NULL) == $value->id) selected="selected" @endif>{{$value->name}}</option>
                                            @endforeach
                                            @endif
                                        </select>
                                    </div>
                                </div>
                            </div>

                                <div class="col-6 mt-5">
                                    <div class="form-group">
                                    <div class="form-group">
                                        <label for="subscriptionId">Subscription</label>
                                        <select class="form-control selectpicker" id="subscriptionId" name="subscriptionId" data-live-search="true">
                                            <option value="">Select subscription</option>
                                            @if(isset($subscriptionId))
                                            @foreach($subscriptionId as $value)
                                            <option value="{{$value->id}}" @if (old('id', isset($subscription->subscriptionId) ? $subscription->subscriptionId : NULL) == $value->id) selected="selected" @endif>{{$value->name}}</option>
                                            @endforeach
                                            @endif
                                        </select>
                                    </div>
                                </div>
                                </div>


                            </div>
                            @if(isset($subscriptionMember->id))
                            <input type="hidden" name="id" value="{{ $subscriptionMember->id }}">
                            @endif
                           
                            <button type="submit" class="btn btn-primary mt-4 pr-4 pl-4">Save</button>
                        </form>
                    </div>
                </div>
            </div>
            <!-- basic form end -->
        </div>
    </div>
</div>

@section('js')
<script src="{{ asset('assets/admin/js/console/subscriptionMember.js') }}"></script>
@append

@endsection

resources/views/admin/subscriptionMember/manage.blade.php
@extends('layout.admin')
@section('content')

<div class="row">
    <!-- data table start -->
    <div class="col-12 mt-5">
        <div class="card">
            <div class="card-body list-grid">

                <div class="row">
                    <div class="col-12">
                        <div class="grid-col control-bar">

                            <div class="row control">
                                <div class="col-6 left-control">

                                    <button type="button" class="btn btn-flat btn-secondary mb-3" onclick="checkAll(1)">Check All</button>
                                    <button type="button" class="btn btn-flat btn-secondary mb-3" onclick="checkAll(0)">Uncheck</button>

                                    <button type="button" class="btn btn-flat btn-danger mb-3" onclick="deleteAll('deleteAllsubscriptionMember','Delete these Blog\'s details?','Are you sure you want to delete these Blog\'s details?');">
                                        Delete</button>

                                    <div class="loading"></div>


                                </div>

                                <div class="col-6 right-control">

                                    <a href="javascript:void(0);" onclick="window.history.back();">
                                        <button type="button" class="btn btn-flat btn-secondary mb-3">Back</button>
                                    </a>


                                    <a href="{{route('blog.index')}}">

                                    <!-- <a href="{{ url('/console/blog') }}"> -->
                                        <button type="button" class="btn btn-flat btn-secondary mb-3">Refresh</button>
                                    </a>

                                    <a href="{{route('subscription-member.create')}}">
                                    <!-- <a href="{{ url('/console/blog/create') }}"> -->
                                        <button type="button" class="btn btn-flat btn-secondary mb-3">Add Subscription Member</button>
                                    </a>

                                </div>

                            </div>

                        </div>
                    </div>
                </div>

                <form method="post" id="deleteAllsubscriptionMember">

                    <div class="data-tables">
                        <table id="subscriptionMemberTable" class="text-center">
                            <thead class="bg-light text-capitalize">
                                <tr>
                                    <th width="5%">Seq.</th>
                                    <th style="width:2px;max-width:2px;"></th>
                                    <th>Id</th>
                                    <th>User ID</th>
                                    <th>subscription Id</th>
                                    <th>Status</th>
                                    <!-- <th>Created</th> -->
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($subscriptionMember as $value)

                                <tr id="item{{$value->id}}">
                                    <td> {{$loop->iteration}} </td>
                                    <td>
                                        <input type="checkbox" class="checkBoxClass" name="deleterecords[]" value="{{$value->id}}">
                                    </td>

                                    <td>{{$value->id}} </td>
                                    <td>{{$value->userId}}</td>
                                    <td>{{$value->subscriptionId}}</td>
                             
                                    <td>
                
                                        <label class="label-switch switch-success">
                                            <input type="checkbox" class="switch switch-bootstrap status" name="status" data-id="{{$value->id}}" @if($value->status == 1) checked="checked" @endif /> 
                                            <span class="lable"></span>
                                        </label>

                                    </td>
                                    <!-- <td>{{$value->created_at}}</td> -->
                                    <td>
                                        <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-toggle="dropdown">
                                            Action
                                        </button>
                                        <div class="dropdown-menu">
                                            <a class="dropdown-item" href="{{route('subscription-member.edit', $value->id)}}">Edit</a>
                                            <a class="dropdown-item" onclick="deleteRecord('{{$value->id}}','Delete this Blog details?','Are you sure you want to delete this Blog details?');">Delete</a>
                                        </div>
                                    </td>

                                </tr>

                                @endforeach

                            </tbody>
                        </table>
                    </div>

                </form>
            </div>
        </div>
    </div>
    <!-- data table end -->
</div>

@section('js')
<script src="{{ asset('assets/admin/js/console/subscriptionMember.js') }}"></script>
@append

@endsection