routes/web.php
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/email', function () {
//     Mail::to('ashish@optimalvirtualemployee.com')->send(new WelcomeMail());
//     return new WelcomeMail();
// });

//Auth::routes();

Route::get('/teacherEarlyMorningReminder', 'CronController@teacherEarlyMorningReminder');
Route::get('/cron/send-to-student-before-one-hour', 'CronController@sendToStudentBeforeOneHour');


Route::get('/login', 'HomeController@showFrontLoginForm')->name('user.login');
Route::post('/account/login', 'HomeController@frontLogin');


Route::get('/admin/login', 'admin\AdminController@login')->name('adminLogin');
Route::post('login', 'admin\AdminController@doLogin')->name('customeLogin');
Route::get('/admin/register', 'admin\AdminController@register');
Route::post('register', 'admin\AdminController@createUser');
Route::get('/', 'HomeController@index')->name('home');

//Route::get('/login', 'HomeController@login')->name('login');
Route::get('/register', 'HomeController@register')->name('register');
Route::get('/forgot-password', 'HomeController@forgotPassword')->name('forgot-password');
Route::get('/account', 'CustomerController@account')->name('account');
// Route::get('/order/{id}', 'CustomerController@orderDetail')->name('orderDetail');
Route::post('/account/register', 'HomeController@storeRegistration');
Route::get('/logout', 'HomeController@logout')->name('logout');
Route::post('/contact', 'HomeController@contactUs');
Route::post('/newsLetter', 'frontend\ProgramController@newsLetter');   

//payment module
// Route::get('/payment', 'PaymentController@payment')->name('payment');

Route::get('/blog', 'HomeController@blog')->name('blog');
Route::get('/blog/{id}', 'HomeController@blogDetail')->name('blogDetail');
Route::post('/get-price-by-measurement', 'HomeController@getPriceByMeasurement');
Route::get('/admin/logout', 'admin\AdminController@logout');

//front program page
Route::get('/program/{id}', 'frontend\ProgramController@index')->name('programDetail');
Route::get('/program-version2/{id}', 'frontend\ProgramController@index1')->name('programDetail1');

//front end program page

// forntend account account dashboard routes

Route::group(['middleware' => ['auth:front']], function () {

Route::post('account-dashboard/{id}', 'frontend\AccountController@accountProfileUpdate');
Route::post('/user/updatePassword/{id}', [
        'as' => 'user.updatePassword',
        'uses' => 'frontend\AccountController@updatePassword'
  ]);
Route::get('/account/dashboard', 'frontend\AccountController@accountDashboard')->name('accountDashboard');
Route::get('/account/profile', 'frontend\AccountController@accountProfile')->name('accountProfile');
Route::get('/account/change-password', 'frontend\AccountController@changePassword')->name('accountChangePassword');
Route::get('/account/manage-session', 'frontend\AccountController@manageSession')->name('manageSession');
Route::get('account/edit-session/{id}/{userId}', ['as' => 'editSession', 'uses' => 'frontend\AccountController@editSession']);

Route::get('account/re-schedule-session/{id}/{userId}', ['as' => 'reScheduleSession', 'uses' => 'frontend\AccountController@reScheduleSession']);

Route::post('/account/meeting/update-session-missed/{id}', ['as' => 'meeting.updateMeetingMissed','uses' => 'frontend\AccountController@updateMeetingMissed']);

Route::post('/account/meeting/update/{id}', ['as' => 'meeting.updateMeeting','uses' => 'frontend\AccountController@updateMeeting']);

Route::get('account/order', 'frontend\AccountController@index');
Route::get('account/show/{id}', 'frontend\AccountController@show')->name('account.show');


//book session module
Route::get('/book-session', 'frontend\BookSessionController@index')->name('book-session');
Route::post('book-session/store/', ['as' => 'bookSession.store', 'uses' => 'frontend\BookSessionController@store']);
Route::post('frontend/subject/getBookSubjectByProgramId', 'frontend\BookSessionController@getBookSubjectByProgramId');
Route::post('frontend/topic/getBookTopicBySubjectId', 'frontend\BookSessionController@getBookTopicBySubjectId');
Route::post('frontend/topic/getPlanByTopicQty', 'frontend\BookSessionController@getPlanByTopicQty');
Route::post('frontend/topic/getPlanByTopicId', 'frontend\BookSessionController@getPlanByTopicId');

Route::get('/payment/{id}', 'frontend\BookSessionController@proceedPayment')->name('payment');
Route::post('frontend/paymentreq', 'frontend\BookSessionController@payment');

// webinar session
Route::get('meeting/webinar/{id}', 'frontend\MeetingController@index');

//end book session

Route::group(['middleware' => ['parentcheck']], function () {


Route::get('/account/manage-children', 'frontend\AccountController@manageChildren')->name('manageChildren');
Route::get('/account/add-children', 'frontend\AccountController@addChildren')->name('addChildren');
Route::get('account/{id}/edit', ['as' => 'account.edit', 'uses' => 'frontend\AccountController@edit']);
Route::put('account/{id}', ['as' => 'account.update', 'uses' => 'frontend\AccountController@update']);
Route::post('account/store', ['as' => 'account.store', 'uses' => 'frontend\AccountController@store']);

});

});

Route::get('/payment-successfull', 'frontend\PageController@paymentSuccess')->name('paymentSuccess');

Route::get('/{slug}', 'frontend\PageController@page')->name('pageDetail');

// admin routes
Route::group(['middleware' => ['auth']], function () {

    Route::get('/admin/permission-denied', 'admin\DashboardController@permissionDenied');

      

    //teacher Meeting Routings
     
     Route::post('admin/teacher-meeting/updateSortorder', 'admin\TeacherMeetingController@updateSortorder');
     Route::post('admin/teacher-meeting/destroyAll', 'admin\TeacherMeetingController@destroyAll');
     Route::post('admin/teacher-meeting/updateStatus', 'admin\TeacherMeetingController@updateStatus');
     Route::resource('admin/teacher-meeting', 'admin\TeacherMeetingController');

     Route::get('admin/teacher-meeting/activate/{id}', 'admin\TeacherMeetingController@meetingActivate');
     Route::post('/teacher-meeting/activate/update/{id}', ['as' => 'teacherMeeting.meetingActivateUpdate','uses' => 'admin\TeacherMeetingController@meetingActivateUpdate']);
 
    //teacher Meeting Routings ends

    //meeting techer scheduling Routings

    //  Route::post('admin/meeting-teacher-scheduling/updateSortorder', 'admin\MeetingTeacherSchedulingController@updateSortorder');
    //  Route::post('admin/meeting-teacher-scheduling/destroyAll', 'admin\MeetingTeacherSchedulingController@destroyAll');
    //  Route::post('admin/meeting-teacher-scheduling/updateStatus', 'admin\MeetingTeacherSchedulingController@updateStatus');
    //  Route::resource('admin/meeting-teacher-scheduling', 'admin\MeetingTeacherSchedulingController');
 
     //meeting techer scheduling Routings ends

    //teacher class Routings

    // Route::post('admin/teacher-class/updateSortorder', 'admin\TeacherClassController@updateSortorder');
    // Route::post('admin/teacher-class/destroyAll', 'admin\TeacherClassController@destroyAll');
    // Route::post('admin/teacher-class/updateStatus', 'admin\TeacherClassController@updateStatus');
    // Route::resource('admin/teacher-class', 'admin\TeacherClassController');
    // Route::post('admin/studentList', 'admin\TeacherClassController@studentList');
 
     //teacher class Routings ends

     //Blog Routings

      
       
         Route::get('admin/user/{id}/edit', ['as' => 'user.edit', 'uses' => 'admin\UserController@edit']);
        
         Route::put('admin/user/{id}', ['as' => 'user.update', 'uses' => 'admin\UserController@update']);


     
        //Meeting Routings ends

       Route::get('/admin/dashboard', 'admin\DashboardController@home');

       Route::group(['middleware' => ['admin']], function () {

           //Meeting Routings

     Route::post('admin/topic/getTopicBySubjectId', 'admin\MeetingController@getTopicBySubjectId');
     Route::post('admin/topic/getTeacherByProgramIDSubjectId', 'admin\MeetingController@getTeacherByProgramIDSubjectId');
     Route::post('admin/meeting/updateSortorder', 'admin\MeetingController@updateSortorder');
     Route::post('admin/meeting/destroyAll', 'admin\MeetingController@destroyAll');
     Route::post('admin/meeting/updateStatus', 'admin\MeetingController@updateStatus');
     Route::get('admin/meeting/activate/{id}', 'admin\MeetingController@meetingActivate');
     Route::post('/meeting/activate/update/{id}', ['as' => 'meeting.meetingActivateUpdate','uses' => 'admin\MeetingController@meetingActivateUpdate']);
     Route::resource('admin/meeting', 'admin\MeetingController');
 
    //Meeting Routings ends

         //Question Catgory Routings
    
       Route::post('admin/question-category/updateSortorder', 'admin\QuestionCategoryController@updateSortorder');
       Route::post('admin/question-category/destroyAll', 'admin\QuestionCategoryController@destroyAll');
       Route::post('admin/question-category/updateStatus', 'admin\QuestionCategoryController@updateStatus');
       Route::resource('admin/question-category', 'admin\QuestionCategoryController');
   
       //QUestion Category Routings ends

       //Question Routings

       Route::post('admin/question/updateSortorder', 'admin\QuestionController@updateSortorder');
       Route::post('admin/question/destroyAll', 'admin\QuestionController@destroyAll');
       Route::post('admin/question/updateStatus', 'admin\QuestionController@updateStatus');
       Route::resource('admin/question', 'admin\QuestionController');
   
       //QUestion Routings ends

       

        Route::get('admin/plan/topic/{programId}/{subjectId}', ['as' => 'plan.topic', 'uses' => 'admin\PlanController@topic']);
    

app/Http/Controllers/frontend/MeetingController.php
<?php

namespace App\Http\Controllers\frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Model\Admin\SessionContant;
use App\Model\Admin\Program;
use App\Model\Admin\Meeting;
use App\Model\Admin\QuestionCategory;
use App\Model\Admin\Question;
use App\Model\Admin\QuestionOption;
use View;
use DB;
class MeetingController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:front');
        $this->middleware(function ($request, $next) {
            $this->userId = Auth::user()->id;
            //$this->accountId = Auth::user()->accountId;
            return $next($request);
        });

        $program = Program::where('status', 1)->orderBy('sortOrder')->get();
        View::share('program', $program);   
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($id)
    {

        $data = array();
        $data["meeting"] = Meeting::findOrFail($id);

        $this->authorize('view', $data["meeting"]);


        $data['questionCat'] = QuestionCategory::orderBy('id','DESC')->get();
        $i=1;
        $questionCategoryId = array();
            foreach ($data["questionCat"] as $key => $value) {
                $questionCategoryId[$i] = json_decode(json_encode($value->id), true);
                 $i++;
        }
        $data['question'] = Question::whereIn('questionCategoryId',$questionCategoryId)->orderBy('id','ASC')->get();

        $data['questionOption'] = QuestionOption::orderBy('id','ASC')->get();
       
        $data["sessionContant"] = SessionContant::where('sessionId',$id)->get();
        $data["pageTitle"] = 'Webinar';
        return view('steve.meeting.webinar')->with($data);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/meeting/activate.blade.php
@extends('layout.admin')
@section('content')

<div class="row">


    <div class="col-lg-12 col-ml-12">
        <div class="row">
            <!-- basic form start -->

            <div class="col-12 mt-5 start-form-sec">

                <div class="card">
                    <div class="card-body">

                        <!-- <h4 class="header-title">Basic form</h4> -->
                         <p id="err" style="color:red;"></p>

                        <form id="Activatefrm" method="post"
                            action="{{url('meeting/activate/update')}}/{{ $meeting->id}}" enctype='multipart/form-data'>

                            {{ csrf_field() }}

                            @if(isset($editStatus))
                            @method('PUT')
                            @endif


                            @if(session()->has('message'))
                            <div class="alert alert-danger">
                                {{ session()->get('message') }}
                            </div>
                            @endif


                            @foreach($errors->all() as $error)
                            <li>{{$error}}</li>
                            @endforeach



                            <div class="row">
                                
                               <div class="col-4 mt-5">
                                    <div class="form-group">
                                        <label for="meetingUrl">Meeting Url</label>
                                        <input type="text" class="form-control" id="meetingUrl" name="meetingUrl" placeholder="Enter Url" value="{{old('meetingUrl',  isset($meeting->meetingUrl) ? $meeting->meetingUrl : NULL)}}">
                                    </div>
                                </div>
                               
                                <div class="col-4 mt-5">
                                    <div class="form-group">
                                        <label for="meetingStatus">Meeting Status</label>
                                       <select class="form-control selectpicker" id="meetingStatus" name="meetingStatus" data-live-search="true">
                                            <option value="">Select Status</option>
                                           
                                            <option value="1" @if (old('meetingStatus', isset($meeting->meetingStatus) ? $meeting->meetingStatus : NULL) == 1) selected="selected" @endif>Active</option>
                                            <option value="0" @if (old('meetingStatus', isset($meeting->meetingStatus) ? $meeting->meetingStatus : NULL) == 0) selected="selected" @endif>Deactivate</option>
                                           
                                        </select>
                                    </div>
                                </div>

                                <div class="col-4 mt-5">
                                    <div class="form-group">
                                        <label for="meetingStatus">Available Teachers</label>
                                       <select class="form-control selectpicker" id="tutorId" name="tutorId"
                                            data-live-search="true">
                                            <option value="">Select Teacher</option>
                                            @if(isset($teacher))
                                            @foreach($teacher as $value)
                                            <option value="{{$value->teacherId}}" @if (old('tutorId', isset($meeting->tutorId) ? $meeting->tutorId : NULL) == $value->teacherId)
                                                selected="selected" @endif>{{$value->teacher->name}}</option>

                                            @endforeach
                                            @endif
                                        </select>
                                    </div>
                                </div>

                            </div>
                        @if(isset($meeting->id))
                        <input type="hidden" name="id" value="{{ $meeting->id }}">
                        @endif
                        <button type="submit" class="btn btn-primary mt-4 pr-4 pl-4">Save</button>

                        </form>

                    </div>
                </div>
            </div>
            <!-- basic form end -->
        </div>
    </div>
</div>


<script type="text/javascript">

$(document).ready(function(){

    $("#Activatefrm").submit(function(){

        if($("#meetingUrl").val()=="")
        {
            $("#err").text("Please enter meeting url");
            $("#meetingUrl").focus();
            return false;
        }
        if($("#meetingStatus").val()=="")
        {
            $("#err").text("Please select meeting status");
            $("#meetingStatus").focus();
            return false;
        }
        });
    });
</script>
@section('js')
<script src="{{ asset('assets/admin/js/console/meeting.js') }}"></script>
@append

@endsection

resources/views/admin/meeting/manage.blade.php
@extends('layout.admin')
@section('content')

<div class="row">
    <!-- data table start -->
    <div class="col-12 mt-5">
        <div class="card">
            <div class="card-body list-grid">

                <div class="row">
                    <div class="col-12">
                        <div class="grid-col control-bar">

                            <div class="row control">
                                <div class="col-6 left-control">

                                    <button type="button" class="btn btn-flat btn-secondary mb-3" onclick="checkAll(1)">Check All</button>
                                    <button type="button" class="btn btn-flat btn-secondary mb-3" onclick="checkAll(0)">Uncheck</button>

                                    <button type="button" class="btn btn-flat btn-danger mb-3" onclick="deleteAll('deleteAllMeeting','Delete these Meeting\'s details?','Are you sure you want to delete these Meeting\'s details?');">
                                        Delete</button>

                                    <div class="loading"></div>


                                </div>

                                <div class="col-6 right-control">

                                    <a href="javascript:void(0);" onclick="window.history.back();">
                                        <button type="button" class="btn btn-flat btn-secondary mb-3">Back</button>
                                    </a>


                                    <a href="{{route('meeting.index')}}">

                                    <!-- <a href="{{ url('/console/meeting') }}"> -->
                                        <button type="button" class="btn btn-flat btn-secondary mb-3">Refresh</button>
                                    </a>

                                   <!--  <a href="{{route('meeting.create')}}">
                                        <button type="button" class="btn btn-flat btn-secondary mb-3">Add Meeting</button>
                                    </a> -->

                                </div>

                            </div>

                        </div>
                    </div>
                </div>

                <form method="post" id="deleteAllMeeting">

                    <div class="data-tables">
                        <table id="meetingTable" class="text-center">
                            <thead class="bg-light text-capitalize">
                                <tr>
                                    <th width="5%">Seq.</th>
                                    <th style="width:2px;max-width:2px;"></th>
                                    <th>Attend By</th>
                                    <th>Program</th>
                                    <th>Subject</th>
                                    <th>Topic</th>
                                    <th>Teacher</th>
                                    <th>Date</th>
                                    <th>Time</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($meeting as $value)

                                <tr id="item{{$value->id}}">
                                    <td> {{$loop->iteration}} </td>
                                    <td>
                                        <input type="checkbox" class="checkBoxClass" name="deleterecords[]" value="{{$value->id}}">
                                    </td>
                                    <td>@isset($value->username->name)
                                    {{$value->username->name}}
                                    @else
                                    NA
                                    @endif</td>
                                    <td>@isset($value->program->name)
                                    {{$value->program->name}}
                                    @else
                                    NA
                                    @endif</td>
                                    <td>@isset($value->subject->name)
                                    {{$value->subject->name}}
                                    @else
                                    NA
                                    @endif</td>
                                    <td>@isset($value->topic->title)
                                    {{$value->topic->title}}
                                    @else
                                    NA
                                    @endif</td>
                                    <td>@isset($value->teacher->name)
                                    {{$value->teacher->name}}
                                    @else
                                    NA
                                    @endif</td>
                                   <td>@isset($value->date)
                                    {{$value->date}}
                                    @else
                                    NA
                                    @endif</td>
                                    <td>@isset($value->timeSlot->id)
                                {{date('h:i',strtotime($value->timeSlot->fromTime))}}- {{date('h:i',strtotime($value->timeSlot->toTime))}}

                                    @else
                                    NA
                                    @endif</td>
                             
                                    <td>
                
                                        <label class="label-switch switch-success">
                                            <input type="checkbox" class="switch switch-bootstrap status" name="status" data-id="{{$value->id}}" @if($value->status == 1) checked="checked" @endif /> 
                                            <span class="lable"></span>
                                        </label>

                                    </td>
                                    <!-- <td>{{$value->created_at}}</td> -->
                                    <td>
                                        <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-toggle="dropdown">
                                            Action
                                        </button>
                                        <div class="dropdown-menu">

                                        <a class="dropdown-item" href="{{route('meeting.edit', $value->id)}}">Edit</a>
                                        @if($value->scheduleStatus == 1)
                                         <a class="dropdown-item" href="{{ url('/admin/meeting/activate', $value->id) }}">Activate</a>
                                        @endif 

                                            <a class="dropdown-item" onclick="deleteRecord('{{$value->id}}','Delete this Meeting details?','Are you sure you want to delete this Meeting details?');">Delete</a>
                                        </div>
                                    </td>

                                </tr>

                                @endforeach

                            </tbody>
                        </table>
                    </div>

                </form>
            </div>
        </div>
    </div>
    <!-- data table end -->
</div>

@section('js')
<script src="{{ asset('assets/admin/js/console/meeting.js') }}"></script>
@append

@endsection