routes/web.php
Route::post('register', 'admin\AdminController@createUser');
Route::get('/', 'HomeController@index')->name('home');

//Route::get('/login', 'HomeController@login')->name('login');
Route::get('/register', 'HomeController@register')->name('register');
Route::get('/forgot-password', 'HomeController@forgotPassword')->name('forgot-password');
Route::get('/account', 'CustomerController@account')->name('account');
// Route::get('/order/{id}', 'CustomerController@orderDetail')->name('orderDetail');
Route::post('/account/register', 'HomeController@storeRegistration');
Route::get('/logout', 'HomeController@logout')->name('logout');
Route::post('/contact', 'HomeController@contactUs');
Route::post('/newsLetter', 'frontend\ProgramController@newsLetter');   

//payment module
// Route::get('/payment', 'PaymentController@payment')->name('payment');

Route::get('/blog', 'HomeController@blog')->name('blog');
Route::get('/blog/{id}', 'HomeController@blogDetail')->name('blogDetail');
Route::post('/get-price-by-measurement', 'HomeController@getPriceByMeasurement');
Route::get('/admin/logout', 'admin\AdminController@logout');

//front program page
Route::get('/program/{id}', 'frontend\ProgramController@index')->name('programDetail');
Route::get('/program-version2/{id}', 'frontend\ProgramController@index1')->name('programDetail1');

//front end program page

// forntend account account dashboard routes

Route::group(['middleware' => ['auth:front']], function () {

Route::post('account-dashboard/{id}', 'frontend\AccountController@accountProfileUpdate');
Route::post('/user/updatePassword/{id}', [
        'as' => 'user.updatePassword',
        'uses' => 'frontend\AccountController@updatePassword'
  ]);
Route::get('/account/dashboard', 'frontend\AccountController@accountDashboard')->name('accountDashboard');
Route::get('/account/profile', 'frontend\AccountController@accountProfile')->name('accountProfile');
Route::get('/account/change-password', 'frontend\AccountController@changePassword')->name('accountChangePassword');
Route::get('/account/manage-session', 'frontend\AccountController@manageSession')->name('manageSession');
Route::get('account/edit-session/{id}/{userId}', ['as' => 'editSession', 'uses' => 'frontend\AccountController@editSession']);

Route::get('account/re-schedule-session/{id}/{userId}', ['as' => 'reScheduleSession', 'uses' => 'frontend\AccountController@reScheduleSession']);

Route::post('/account/meeting/update-session-missed/{id}', ['as' => 'meeting.updateMeetingMissed','uses' => 'frontend\AccountController@updateMeetingMissed']);

Route::post('/account/meeting/update/{id}', ['as' => 'meeting.updateMeeting','uses' => 'frontend\AccountController@updateMeeting']);

Route::get('account/order', 'frontend\AccountController@index');
Route::get('account/show/{id}', 'frontend\AccountController@show')->name('account.show');


//book session module
Route::get('/book-session', 'frontend\BookSessionController@index')->name('book-session');
Route::post('book-session/store/', ['as' => 'bookSession.store', 'uses' => 'frontend\BookSessionController@store']);
Route::post('frontend/subject/getBookSubjectByProgramId', 'frontend\BookSessionController@getBookSubjectByProgramId');
Route::post('frontend/topic/getBookTopicBySubjectId', 'frontend\BookSessionController@getBookTopicBySubjectId');
Route::post('frontend/topic/getPlanByTopicQty', 'frontend\BookSessionController@getPlanByTopicQty');
Route::post('frontend/topic/getPlanByTopicId', 'frontend\BookSessionController@getPlanByTopicId');

Route::get('/payment/{id}', 'frontend\BookSessionController@proceedPayment')->name('payment');
Route::post('frontend/paymentreq', 'frontend\BookSessionController@payment');

// webinar session
Route::get('meeting/webinar/{id}', 'frontend\MeetingController@index');

//end book session

Route::group(['middleware' => ['parentcheck']], function () {


Route::get('/account/manage-children', 'frontend\AccountController@manageChildren')->name('manageChildren');
Route::get('/account/add-children', 'frontend\AccountController@addChildren')->name('addChildren');
Route::get('account/{id}/edit', ['as' => 'account.edit', 'uses' => 'frontend\AccountController@edit']);
Route::put('account/{id}', ['as' => 'account.update', 'uses' => 'frontend\AccountController@update']);
Route::post('account/store', ['as' => 'account.store', 'uses' => 'frontend\AccountController@store']);

});

});

Route::get('/payment-successfull', 'frontend\PageController@paymentSuccess')->name('paymentSuccess');

Route::get('/{slug}', 'frontend\PageController@page')->name('pageDetail');

// admin routes
Route::group(['middleware' => ['auth']], function () {

    Route::get('/admin/permission-denied', 'admin\DashboardController@permissionDenied');

      

    //teacher Meeting Routings
     
     Route::post('admin/teacher-meeting/updateSortorder', 'admin\TeacherMeetingController@updateSortorder');
     Route::post('admin/teacher-meeting/destroyAll', 'admin\TeacherMeetingController@destroyAll');
     Route::post('admin/teacher-meeting/updateStatus', 'admin\TeacherMeetingController@updateStatus');
     Route::resource('admin/teacher-meeting', 'admin\TeacherMeetingController');

     Route::get('admin/teacher-meeting/activate/{id}', 'admin\TeacherMeetingController@meetingActivate');
     Route::post('/teacher-meeting/activate/update/{id}', ['as' => 'teacherMeeting.meetingActivateUpdate','uses' => 'admin\TeacherMeetingController@meetingActivateUpdate']);
 
    //teacher Meeting Routings ends

    //meeting techer scheduling Routings

    //  Route::post('admin/meeting-teacher-scheduling/updateSortorder', 'admin\MeetingTeacherSchedulingController@updateSortorder');
    //  Route::post('admin/meeting-teacher-scheduling/destroyAll', 'admin\MeetingTeacherSchedulingController@destroyAll');
    //  Route::post('admin/meeting-teacher-scheduling/updateStatus', 'admin\MeetingTeacherSchedulingController@updateStatus');
    //  Route::resource('admin/meeting-teacher-scheduling', 'admin\MeetingTeacherSchedulingController');
 
     //meeting techer scheduling Routings ends

    //teacher class Routings

    // Route::post('admin/teacher-class/updateSortorder', 'admin\TeacherClassController@updateSortorder');
    // Route::post('admin/teacher-class/destroyAll', 'admin\TeacherClassController@destroyAll');
    // Route::post('admin/teacher-class/updateStatus', 'admin\TeacherClassController@updateStatus');
    // Route::resource('admin/teacher-class', 'admin\TeacherClassController');
    // Route::post('admin/studentList', 'admin\TeacherClassController@studentList');
 
     //teacher class Routings ends

     //Blog Routings

      
       
         Route::get('admin/user/{id}/edit', ['as' => 'user.edit', 'uses' => 'admin\UserController@edit']);
        
         Route::put('admin/user/{id}', ['as' => 'user.update', 'uses' => 'admin\UserController@update']);


     
        //Meeting Routings ends

       Route::get('/admin/dashboard', 'admin\DashboardController@home');

       Route::group(['middleware' => ['admin']], function () {

           //Meeting Routings

     Route::post('admin/topic/getTopicBySubjectId', 'admin\MeetingController@getTopicBySubjectId');
     Route::post('admin/topic/getTeacherByProgramIDSubjectId', 'admin\MeetingController@getTeacherByProgramIDSubjectId');
     Route::post('admin/meeting/updateSortorder', 'admin\MeetingController@updateSortorder');
     Route::post('admin/meeting/destroyAll', 'admin\MeetingController@destroyAll');
     Route::post('admin/meeting/updateStatus', 'admin\MeetingController@updateStatus');
     Route::get('admin/meeting/activate/{id}', 'admin\MeetingController@meetingActivate');
     Route::post('/meeting/activate/update/{id}', ['as' => 'meeting.meetingActivateUpdate','uses' => 'admin\MeetingController@meetingActivateUpdate']);
     Route::resource('admin/meeting', 'admin\MeetingController');
 
    //Meeting Routings ends

         //Question Catgory Routings
    
       Route::post('admin/question-category/updateSortorder', 'admin\QuestionCategoryController@updateSortorder');
       Route::post('admin/question-category/destroyAll', 'admin\QuestionCategoryController@destroyAll');
       Route::post('admin/question-category/updateStatus', 'admin\QuestionCategoryController@updateStatus');
       Route::resource('admin/question-category', 'admin\QuestionCategoryController');
   
       //QUestion Category Routings ends

       //Question Routings

       Route::post('admin/question/updateSortorder', 'admin\QuestionController@updateSortorder');
       Route::post('admin/question/destroyAll', 'admin\QuestionController@destroyAll');
       Route::post('admin/question/updateStatus', 'admin\QuestionController@updateStatus');
       Route::resource('admin/question', 'admin\QuestionController');
   
       //QUestion Routings ends

       

        Route::get('admin/plan/topic/{programId}/{subjectId}', ['as' => 'plan.topic', 'uses' => 'admin\PlanController@topic']);
    
        Route::post('admin/plan/delete/{id}', ['as' => 'plan.delete', 'uses' => 'admin\PlanController@delete']);
    
        Route::resource('admin/plan', 'admin\PlanController');
    
       //Testimonial Routings
    
       Route::post('admin/testimonial/updateSortorder', 'admin\TestimonialController@updateSortorder');
       Route::post('admin/testimonial/destroyAll', 'admin\TestimonialController@destroyAll');
       Route::post('admin/testimonial/updateStatus', 'admin\TestimonialController@updateStatus');
       Route::resource('admin/testimonial', 'admin\TestimonialController');
    
       //Testimonial Routings ends
    
    
        //Program Routings
    
        Route::post('admin/program/updateSortorder', 'admin\ProgramController@updateSortorder');
        Route::post('admin/program/destroyAll', 'admin\ProgramController@destroyAll');
        Route::post('admin/program/updateStatus', 'admin\ProgramController@updateStatus');
        Route::resource('admin/program', 'admin\ProgramController');

resources/views/admin/plan/manage.blade.php
@extends('layout.admin')
@section('content')

<div class="row">
    <!-- data table start -->
    <div class="col-12 mt-5">
        <div class="card">
            <div class="card-body list-grid">

                <div class="row">
                    <div class="col-12">
                        <div class="grid-col control-bar">

                            <div class="row control">
                                <!-- <div class="col-6 left-control">

                                    <button type="button" class="btn btn-flat btn-secondary mb-3" onclick="checkAll(1)">Check All</button>
                                    <button type="button" class="btn btn-flat btn-secondary mb-3" onclick="checkAll(0)">Uncheck</button>

                                    <button type="button" class="btn btn-flat btn-danger mb-3" onclick="deleteAll('deleteAllPlan','Delete these Plan\'s details?','Are you sure you want to delete these Plan\'s details?');">
                                        Delete</button>

                                    <div class="loading"></div>


                                </div> -->

                                <!-- <div class="col-6 right-control">

                                    <a href="javascript:void(0);" onclick="window.history.back();">
                                        <button type="button" class="btn btn-flat btn-secondary mb-3">Back</button>
                                    </a>


                                    <a href="{{route('plan.index')}}">

                                    <a href="{{ url('/console/plan') }}"> -->
                                <!-- <button type="button" class="btn btn-flat btn-secondary mb-3">Refresh</button> 
                                    </a>
 <a href="{{route('plan.create')}}"> 
                                     <a href="{{ url('/console/bannner/create') }}"> 
                                         <button type="button" class="btn btn-flat btn-secondary mb-3">Add Plan</button> 
                                  </a> 

                                </div> -->

                            </div>

                        </div>
                    </div>
                </div>

                <form method="post" id="deleteAllPlan">

                    <div class="data-tables">
                    <table id="planTable" class="text-center">
                        <thead class="bg-light text-capitalize">
                            <tr>
                                <th width="5%">Seq.</th>
                                <!-- <th style="width:2px;max-width:2px;"></th> -->
                                <th>Program</th>
                                <th>Subject</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($plan as $value)

                            <tr id="item{{$value->id}}">
                                <td> {{$loop->iteration}} </td>
                                <!-- <td>
                                    <input type="checkbox" class="checkBoxClass" name="deleterecords[]"
                                        value="{{$value->id}}">
                                </td> -->

                                <td>@isset($value->programName){{$value->programName}}@else NA @endif </td>
                                <td>@isset($value->subjectName){{$value->subjectName}}@else NA @endif</td>
                                <!-- <td>{{$value->planText}}</td>
                                <td>{{$value->planSlogan}}</td> -->

                                <!-- <td>

                                    <label class="label-switch switch-success">
                                        <input type="checkbox" class="switch switch-bootstrap status" name="status"
                                            data-id="{{$value->id}}" @if($value->status == 1) checked="checked" @endif
                                        />
                                        <span class="lable"></span>
                                    </label>

                                </td> -->
                                <!-- <td>{{$value->created_at}}</td> -->
                                <td>

                                <a href="{{route('plan.topic',['programId' => $value->programId, 'subjectId' => $value->subjectId])}}" >

                                <button class="btn btn-secondary btn-sm " type="button" >
                                            Manage plan by topic
                                </button>

                                </a>

                                </td>

                            </tr>

                            @endforeach

                        </tbody>
                    </table>
            </div>

            </form>
        </div>
    </div>
</div>
<!-- data table end -->
</div>

@section('js')
<script src="{{ asset('assets/admin/js/console/plan.js') }}"></script>
@append

@endsection

resources/views/admin/plan/topic.blade.php
@extends('layout.admin')
@section('content')

<div class="row">


    <div class="col-lg-12 col-ml-12">
        <div class="row">
            <!-- basic form start -->

            <div class="col-12 mt-5 start-form-sec">

                <div class="card">
                    <div class="card-body">

                        <!-- <h4 class="header-title">Basic form</h4> -->
                        <p id="err" style="color:red;"></p>

                        <form id="planForm" method="post"
                            action="@if(isset($editStatus)){{ route('plan.update', $topic->id) }} @else {{ route('plan.store')}}@endif"
                            enctype='multipart/form-data'>

                            {{ csrf_field() }}

                            @if(isset($editStatus))
                            @method('PUT')
                            @endif


                            @if(session()->has('message'))
                            <div class="alert alert-success">
                                {{ session()->get('message') }}
                            </div>
                            @endif


                            @foreach($errors->all() as $error)
                            <li>{{$error}}</li>
                            @endforeach

                            <div class="row">

                                <div class="col-4 mt-5">
                                    <div class="form-group">
                                        <label for="topic">Topic</label>
                                        <div class="loading"></div>
                                        <select class="form-control selectpicker" id="topicId" name="topicId"
                                            data-live-search="true">
                                            <option value="">Select Topic</option>
                                            @if(isset($topic))
                                            @foreach($topic as $value)
                                            <option value="{{$value->id}}" @if (old('topicId', isset($topic->
                                                topicId) ? $topic->topicId : NULL) == $value->id)
                                                selected="selected" @endif>{{$value->title}}</option>

                                            @endforeach
                                            @endif
                                        </select>
                                    </div>
                                </div>


                                <div class="col-4 mt-5">
                                    <div class="form-group">
                                        <label for="quantity">Quantity</label>
                                        <div class="loading"></div>
                                        <select class="form-control selectpicker" id="quantity" name="quantity">
                                            <option value="">Select Quantity</option>

                                            <option value="1" @if (old('quantity', isset($topic->
                                                quantity) ? $topic->quantity : NULL) == 1)
                                                selected="selected" @endif>1</option>

                                            <option value="2" @if (old('quantity', isset($topic->
                                                quantity) ? $topic->quantity : NULL) == 2)
                                                selected="selected" @endif>2</option>

                                            <option value="3" @if (old('quantity', isset($topic->
                                                quantity) ? $topic->quantity : NULL) == 3)
                                                selected="selected" @endif>3</option>

                                            <option value="4" @if (old('quantity', isset($topic->
                                                quantity) ? $topic->quantity : NULL) == 4)
                                                selected="selected" @endif>4</option>

                                            <option value="5" @if (old('quantity', isset($topic->
                                                quantity) ? $topic->quantity : NULL) == 5)
                                                selected="selected" @endif>5</option>


                                        </select>
                                    </div>
                                </div>


                                <div class="col-4 mt-5">
                                    <div class="form-group">
                                        <label for="amount">Amount</label>
                                        <input type="text" class="form-control" id="amount" name="amount"
                                            placeholder="Enter amount"
                                            value="{{old('amount',  isset($topic->amount) ? $topic->amout : NULL)}}">
                                    </div>
                                </div>




                            </div>

                            @if(isset($topic->id))
                            <input type="hidden" name="id" value="{{ $topic->id }}">
                            @endif
                            <input type="hidden" name="programId" value="{{ $programId }}">
                            <input type="hidden" name="subjectId" value="{{ $subjectId}}">

                            <button type="submit" class="btn btn-primary mt-4 pr-4 pl-4">Save</button>
                        </form>
                    </div>






                </div>
            </div>
            <!-- basic form end -->
        </div>



        <div class="row">


            <div class="col-12 mt-5 start-form-sec">

                <div class="card">
                    <div class="card-body">

                        <!-- <h4 class="header-title">Basic form</h4> -->
                        <p id="err" style="color:red;"></p>

                        <div class="data-tables">
                            <table id="planTable" class="text-center">
                                <thead class="bg-light text-capitalize">
                                    <tr>
                                        <th width="5%">Seq.</th>
                                        <!-- <th style="width:2px;max-width:2px;"></th> -->
                                        <th>Topic</th>
                                        <th>Quantity</th>
                                        <th>Amount</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($plan as $value)

                                    <tr id="item{{$value->id}}">
                                        <td> {{$loop->iteration}} </td>
                                        <!-- <td>
                                    <input type="checkbox" class="checkBoxClass" name="deleterecords[]"
                                        value="{{$value->id}}">
                                </td> -->

                                        <td>@isset($value->title){{$value->title}}@else NA @endif</td>
                                        <td>@isset($value->quantity){{$value->quantity}}@else NA @endif</td>
                                        <td>@isset($value->amount){{$value->amount}}@else NA @endif</td>
                                        <!-- <td>{{$value->planText}}</td>
                                <td>{{$value->planSlogan}}</td> -->

                                        <!-- <td>

                                    <label class="label-switch switch-success">
                                        <input type="checkbox" class="switch switch-bootstrap status" name="status"
                                            data-id="{{$value->id}}" @if($value->status == 1) checked="checked" @endif
                                        />
                                        <span class="lable"></span>
                                    </label>

                                </td> -->
                                        <!-- <td>{{$value->created_at}}</td> -->
                                        <td>


                                            <form id="planDeleteForm" method="post"
                                                action="{{route('plan.delete', $value->id) }}">

                                                {{ csrf_field() }}

                                                <input type="hidden" name="programId" value="{{ $programId }}">
                            <input type="hidden" name="subjectId" value="{{ $subjectId}}">


                                                <button class="btn btn-secondary btn-sm " type="submit">
                                                    Delete
                                                </button>


                                            </form>

                                        </td>

                                    </tr>

                                    @endforeach

                                </tbody>
                            </table>
                        </div>
                    </div>






                </div>
            </div>
            <!-- basic form end -->
        </div>
    </div>
</div>

@section('js')
<script src="{{ asset('assets/admin/js/console/plan.js') }}"></script>
@append

<script type="text/javascript">
$(document).ready(function() {

            $("#planForm").submit(function(){

                if($("#topicId").val()=="")
                {
                    $("#err").text("Please select topic");
                    $("#topicId").focus();
                    return false;
                }
                if($("#quantity").val()=="")
                {
                    $("#err").text("Please select quantity");
                    $("#quantity").focus();
                    return false;
                }
                if($("#amount").val()=="")
                {
                    $("#err").text("Please enter amount");
                    $("#amount").focus();
                    return false;
                }
                if($("#bannerSloganText").val()=="")
                {
                    $("#err").text("Please enter your bannerSloganText");
                    $("#bannerSloganText").focus();
                    return false;
                }
                });
            });
</script>

@endsection