routes/web.php
         Route::post('admin/subscription-member/updateSortorder', 'admin\SubscriptionMemberController@updateSortorder');
         Route::post('admin/subscription-member/destroyAll', 'admin\SubscriptionMemberController@destroyAll');
         Route::post('admin/subscription-member/updateStatus', 'admin\SubscriptionMemberController@updateStatus');
         Route::resource('admin/subscription-member', 'admin\SubscriptionMemberController');
     
         //Subscription Member Routings ends
    
           
    
        //meeting techer scheduling Routings
    
        //  Route::post('admin/meeting-teacher-scheduling/updateSortorder', 'admin\MeetingTeacherSchedulingController@updateSortorder');
        //  Route::post('admin/meeting-teacher-scheduling/destroyAll', 'admin\MeetingTeacherSchedulingController@destroyAll');
        //  Route::post('admin/meeting-teacher-scheduling/updateStatus', 'admin\MeetingTeacherSchedulingController@updateStatus');
        //  Route::resource('admin/meeting-teacher-scheduling', 'admin\MeetingTeacherSchedulingController');
     
         //meeting techer scheduling Routings ends
    
        //teacher class Routings
    
        Route::post('admin/teacher-class/updateSortorder', 'admin\TeacherClassController@updateSortorder');
        Route::post('admin/teacher-class/destroyAll', 'admin\TeacherClassController@destroyAll');
        Route::post('admin/teacher-class/updateStatus', 'admin\TeacherClassController@updateStatus');
        Route::resource('admin/teacher-class', 'admin\TeacherClassController');
        Route::post('admin/studentList', 'admin\TeacherClassController@studentList');
     
         //teacher class Routings ends
    
         //Blog Routings
    
         Route::post('admin/blog/updateSortorder', 'admin\BlogController@updateSortorder');
         Route::post('admin/blog/destroyAll', 'admin\BlogController@destroyAll');
         Route::post('admin/blog/updateStatus', 'admin\BlogController@updateStatus');
         Route::resource('admin/blog', 'admin\BlogController');
     
         //Blog Routings ends
    
        //Banner Routings
    
         Route::post('admin/banner/updateSortorder', 'admin\BannerController@updateSortorder');
         Route::post('admin/banner/destroyAll', 'admin\BannerController@destroyAll');
         Route::post('admin/banner/updateStatus', 'admin\BannerController@updateStatus');
         Route::resource('admin/banner', 'admin\BannerController');
     
         //Banner Routings ends
    
    
         //Contact Routings
    
         Route::post('admin/contact/updateSortorder', 'admin\ContactController@updateSortorder');
         Route::post('admin/contact/destroyAll', 'admin\ContactController@destroyAll');
         Route::post('admin/contact/updateStatus', 'admin\ContactController@updateStatus');
         Route::resource('admin/contact', 'admin\ContactController');
     
         //Contact Routings ends
    
         //Blog Routings
    
         Route::post('admin/user/updateSortorder', 'admin\UserController@updateSortorder');
         Route::post('admin/user/destroyAll', 'admin\UserController@destroyAll');
         Route::post('admin/user/updateStatus', 'admin\UserController@updateStatus');
         Route::resource('admin/user', 'admin\UserController');
     
         //Blog Routings ends
    
        //Master/States Routings
    
         Route::post('admin/state/updateSortorder', 'admin\StatesController@updateSortorder');
         Route::post('admin/state/destroyAll', 'admin\StatesController@destroyAll');
         Route::post('admin/state/updateStatus', 'admin\StatesController@updateStatus');
         Route::resource('admin/state', 'admin\StatesController');
     
         //Master/States Routings ends
    
        //Master/Time-Slot Routings
    
         Route::post('admin/time-slot/updateSortorder', 'admin\TimeSlotController@updateSortorder');
         Route::post('admin/time-slot/destroyAll', 'admin\TimeSlotController@destroyAll');
         Route::post('admin/time-slot/updateStatus', 'admin\TimeSlotController@updateStatus');
         Route::resource('admin/time-slot', 'admin\TimeSlotController');
     
         //Master/Time-Slot  Routings ends
    
        //Topic Routings
         
         Route::post('admin/topic/updateSortorder', 'admin\TopicController@updateSortorder');
         Route::post('admin/topic/destroyAll', 'admin\TopicController@destroyAll');
         Route::post('admin/topic/updateStatus', 'admin\TopicController@updateStatus');
         Route::resource('admin/topic', 'admin\TopicController');
     
         //Topic Routings ends
    
           //Order Routings
    
        Route::post('admin/order/updateSortorder', 'admin\OrderController@updateSortorder');
        Route::post('admin/order/destroyAll', 'admin\OrderController@destroyAll');
        Route::post('admin/order/updateStatus', 'admin\OrderController@updateStatus');
        Route::resource('admin/order', 'admin\OrderController');
    
        //Order Routings endss





    });    

    /*

    //-------Console Product Routing---------//

    //Route for passing multiple parameters
    //View Syntax {route('prom.edit',['id' => $value->id,'catId' => 1])}}
    //------
    //Route::get('admin/promoter/edit/{id}/{catId}', ['as' => 'prom.edit', 'uses' => 'admin\PromoterController@edit']);
    Route::post('admin/product/updateSortorder', 'admin\ProductController@updateSortorder');
    Route::post('admin/product/destroyAll', 'admin\ProductController@destroyAll');
    Route::post('admin/product/updateStatus', 'admin\ProductController@updateStatus');
    Route::get('/admin/product/dimension/{productId}', 'admin\ProductController@dimension');
    Route::resource('admin/product', 'admin\ProductController');

    //Product Dimension Routings

    Route::get('admin/product-dimension/{productId}/', ['as' => 'productDimension.index', 'uses' => 'admin\ProductDimensionController@index']);
    Route::get('admin/product-dimension/create/{productId}/', ['as' => 'productDimension.create', 'uses' => 'admin\ProductDimensionController@create']);
    Route::get('admin/product-dimension/edit/{id}/{productId}/', ['as' => 'productDimension.edit', 'uses' => 'admin\ProductDimensionController@edit']);
    Route::post('admin/product-dimension/store/', ['as' => 'productDimension.store', 'uses' => 'admin\ProductDimensionController@store']);
    Route::put('admin/product-dimension/update/', ['as' => 'productDimension.update', 'uses' => 'admin\ProductDimensionController@update']);
    Route::delete('admin/product-dimension/destroy/', ['as' => 'productDimension.delete', 'uses' => 'admin\ProductDimensionController@destroy']);
    Route::post('admin/product-dimension/destroyAll', 'admin\ProductDimensionController@destroyAll');
    Route::post('admin/product-dimension/updateStatus', 'admin\ProductDimensionController@updateStatus');
    Route::post('admin/product-dimension/updateSortorder', 'admin\ProductDimensionController@updateSortorder');


    //Product Dimension Routings ends


    //Shutter Type Routings

    Route::get('admin/shutter-type/{productId}/', ['as' => 'shutterType.index', 'uses' => 'admin\ShutterTypeController@index']);
    Route::get('admin/shutter-type/create/{productId}/', ['as' => 'shutterType.create', 'uses' => 'admin\ShutterTypeController@create']);
    Route::get('admin/shutter-type/edit/{id}/{productId}/', ['as' => 'shutterType.edit', 'uses' => 'admin\ShutterTypeController@edit']);
    Route::post('admin/shutter-type/store/', ['as' => 'shutterType.store', 'uses' => 'admin\ShutterTypeController@store']);
    Route::put('admin/shutter-type/update/', ['as' => 'shutterType.update', 'uses' => 'admin\ShutterTypeController@update']);
    Route::delete('admin/shutter-type/destroy/', ['as' => 'shutterType.delete', 'uses' => 'admin\ShutterTypeController@destroy']);
    Route::post('admin/shutter-type/destroyAll', 'admin\ShutterTypeController@destroyAll');
    Route::post('admin/shutter-type/updateStatus', 'admin\ShutterTypeController@updateStatus');
    Route::post('admin/shutter-type/updateSortorder', 'admin\ShutterTypeController@updateSortorder');


    //Shutter Type Routings ends

    //Shutter Style Routings

    Route::get('admin/shutter-style/{productId}/', ['as' => 'shutterStyle.index', 'uses' => 'admin\ShutterStyleController@index']);
    Route::get('admin/shutter-style/create/{productId}/', ['as' => 'shutterStyle.create', 'uses' => 'admin\ShutterStyleController@create']);
    Route::get('admin/shutter-style/edit/{id}/{productId}/', ['as' => 'shutterStyle.edit', 'uses' => 'admin\ShutterStyleController@edit']);
    Route::post('admin/shutter-style/store/', ['as' => 'shutterStyle.store', 'uses' => 'admin\ShutterStyleController@store']);
    Route::put('admin/shutter-style/update/', ['as' => 'shutterStyle.update', 'uses' => 'admin\ShutterStyleController@update']);
    Route::delete('admin/shutter-style/destroy/', ['as' => 'shutterStyle.delete', 'uses' => 'admin\ShutterStyleController@destroy']);
    Route::post('admin/shutter-style/destroyAll', 'admin\ShutterStyleController@destroyAll');
    Route::post('admin/shutter-style/updateStatus', 'admin\ShutterStyleController@updateStatus');
    Route::post('admin/shutter-style/updateSortorder', 'admin\ShutterStyleController@updateSortorder');


    //Shutter Style Routings ends

    //Color Routings

    Route::get('admin/color/{productId}/', ['as' => 'color.index', 'uses' => 'admin\ColorController@index']);
    Route::get('admin/color/create/{productId}/', ['as' => 'color.create', 'uses' => 'admin\ColorController@create']);
    Route::get('admin/color/edit/{id}/{productId}/', ['as' => 'color.edit', 'uses' => 'admin\ColorController@edit']);
    Route::post('admin/color/store/', ['as' => 'color.store', 'uses' => 'admin\ColorController@store']);
    Route::put('admin/color/update/', ['as' => 'color.update', 'uses' => 'admin\ColorController@update']);

app/Http/Controllers/admin/StatesController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Admin\States;
use Illuminate\Support\Facades\Auth;


class StatesController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware(function ($request, $next) {
            $this->userId = Auth::user()->id;
            $this->accountId = Auth::user()->accountId;
            return $next($request);
        });
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = array();

        $data["states"] = States::orderBy('sortOrder')->get();
      

        $data["pageTitle"] = 'Manage State';
        $data["activeMenu"] = 'master';
        $data["activeSubMenu"] = 'state';
        return view('admin.states.manage')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = array();

        $data["pageTitle"] = 'Add State';
        $data["activeMenu"] = 'master';
        $data["activeSubMenu"] = 'state';
        return view('admin.states.create')->with($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate(request(), [
            'name' => 'required|unique:states',
        ],
        [
            'name.required'=> 'State name is required',
            'unique' => 'The state name has already been taken.',
        ]);

        $states = new States();

        $states->name = $request->input('name');
       
        $states->status = 1;
        $states->sortOrder = 1;

        $states->increment('sortOrder');

        $states->save();

        return redirect()->route('state.index')->with('message', 'State Added Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
        $data = array();

        $data['states'] = States::find($id);

        $data["editStatus"] = 1;
        $data["pageTitle"] = 'Update State';
        $data["activeMenu"] = 'master';
        $data["activeSubMenu"] = 'state';
        return view('admin.states.create')->with($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {

        $this->validate(request(), [
            'name' => 'required',
        ]);
        
        $id = $request->input('id');

        $states = States::find($id);


        $states->name = $request->input('name');

        $states->save();

        return redirect()->route('state.index')->with('message', 'State Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        $id = $request->id;
        $states = States::find($id);
        $states->delete($id);

        return response()->json([
            'status' => 1,
            'message' => 'Delete Successfull',
            'response' => $request->id
        ]);
    }

    /**
     * Remove all selected resource from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function destroyAll(Request $request)
    {

        $record = $request->input('deleterecords');

        if (isset($record) && !empty($record)) {

            foreach ($record as $id) {
                $states = States::find($id);
                $states->delete();
            }
        }

        return response()->json([
            'status' => 1,
            'message' => 'Delete Successfull',
            'response' => ''
        ]);
    }

    /**
     * Update SortOrder.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function updateSortorder(Request $request)
    {
        $data = $request->records;
        $decoded_data = json_decode($data);
        $result = 0;

        if (is_array($decoded_data)) {
            foreach ($decoded_data as $values) {

                $id = $values->id;
                $states = States::find($id);
                $states->sortOrder = $values->position;
                $result = $states->save();
            }
        }

        if ($result) {
            $response = array('status' => 1, 'message' => 'Sort order updated', 'response' => $data);
        } else {
            $response = array('status' => 0, 'message' => 'Something went wrong', 'response' => $data);
        }

        return response()->json($response);
    }

    /**
     * Update Status resource from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function updateStatus(Request $request)
    {
        $status = $request->status;
        $id = $request->id;

        $states = States::find($id);
        $states->status = $status;
        $result = $states->save();

        if ($result) {
            $response = array('status' => 1, 'message' => 'Status updated', 'response' => '');
        } else {
            $response = array('status' => 0, 'message' => 'Something went wrong', 'response' => '');
        }

        return response()->json($response);
    }

}

resources/views/admin/states/create.blade.php
@extends('layout.admin')
@section('content')

<div class="row">


<div class="col-lg-12 col-ml-12">
        <div class="row">
            <!-- basic form start -->

            <div class="col-12 mt-5 start-form-sec">

                <div class="card">
                    <div class="card-body">

                        <!-- <h4 class="header-title">Basic form</h4> -->
                        <p id="err" style="color:red;"></p>

                        <form id="statesForm" method="post" action="@if(isset($editStatus)){{ route('state.update', $states->id) }} @else {{ route('state.store')}}@endif" enctype='multipart/form-data'>

                            {{ csrf_field() }}

                            @if(isset($editStatus))
                            @method('PUT')
                            @endif


                            @if(session()->has('message'))
                            <div class="alert alert-danger">
                                {{ session()->get('message') }}
                            </div>
                            @endif


                            @foreach($errors->all() as $error)
                            <li>{{$error}}</li>
                            @endforeach

                            <div class="row">

                                <div class="col-12 mt-5">
                                    <div class="form-group">
                                        <label for="name">State Name</label>
                                        <input type="text" class="form-control" id="name" name="name" placeholder="Enter State Name" value="{{old('name',  isset($states->name) ? $states->name : NULL)}}">
                                    </div>
                                </div>
                            </div>

                            @if(isset($states->id))
                            <input type="hidden" name="id" value="{{ $states->id }}">
                            @endif
                           
                            <button type="submit" class="btn btn-primary mt-4 pr-4 pl-4">Save</button>
                        </form>
                    </div>
                </div>
            </div>
            <!-- basic form end -->
        </div>
    </div>
</div>

@section('js')
<script src="{{ asset('assets/admin/js/console/states.js') }}"></script>
@append

<script type="text/javascript">

$(document).ready(function(){

    $("#statesForm").submit(function(){

        if($("#name").val()=="")
        {
            $("#err").text("Please enter state name");
            $("#name").focus();
            return false;
        }
        });
    });
 
</script>
@endsection

resources/views/admin/states/manage.blade.php
@extends('layout.admin')
@section('content')

<div class="row">
    <!-- data table start -->
    <div class="col-12 mt-5">
        <div class="card">
            <div class="card-body list-grid">

                <div class="row">
                    <div class="col-12">
                        <div class="grid-col control-bar">

                            <div class="row control">
                                <div class="col-6 left-control">

                                    <button type="button" class="btn btn-flat btn-secondary mb-3" onclick="checkAll(1)">Check All</button>
                                    <button type="button" class="btn btn-flat btn-secondary mb-3" onclick="checkAll(0)">Uncheck</button>

                                    <button type="button" class="btn btn-flat btn-danger mb-3" onclick="deleteAll('deleteAllStates','Delete these States\'s details?','Are you sure you want to delete these State\'s details?');">
                                        Delete</button>

                                    <div class="loading"></div>


                                </div>

                                <div class="col-6 right-control">

                                    <a href="javascript:void(0);" onclick="window.history.back();">
                                        <button type="button" class="btn btn-flat btn-secondary mb-3">Back</button>
                                    </a>


                                    <a href="{{route('state.index')}}">

                                    <!-- <a href="{{ url('/console/state') }}"> -->
                                        <button type="button" class="btn btn-flat btn-secondary mb-3">Refresh</button>
                                    </a>

                                    <a href="{{route('state.create')}}">
                                    <!-- <a href="{{ url('/console/state/create') }}"> -->
                                        <button type="button" class="btn btn-flat btn-secondary mb-3">Add States</button>
                                    </a>

                                </div>

                            </div>

                        </div>
                    </div>
                </div>

                <form method="post" id="deleteAllStates">

                    <div class="data-tables">
                        <table id="statesTable" class="text-center">
                            <thead class="bg-light text-capitalize">
                                <tr>
                                    <th width="5%">Seq.</th>
                                    <th style="width:2px;max-width:2px;"></th>
                                    <th>Name</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($states as $value)

                                <tr id="item{{$value->id}}">
                                    <td> {{$loop->iteration}} </td>
                                    <td>
                                        <input type="checkbox" class="checkBoxClass" name="deleterecords[]" value="{{$value->id}}">
                                    </td>

                                    <td>@isset($value->name){{$value->name}}@else NA @endif </td> 
                                    <td>
                
                                        <label class="label-switch switch-success">
                                            <input type="checkbox" class="switch switch-bootstrap status" name="status" data-id="{{$value->id}}" @if($value->status == 1) checked="checked" @endif /> 
                                            <span class="lable"></span>
                                        </label>

                                    </td>
                                    <!-- <td>{{$value->created_at}}</td> -->
                                    <td>
                                        <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-toggle="dropdown">
                                            Action
                                        </button>
                                        <div class="dropdown-menu">
                                            <a class="dropdown-item" href="{{route('state.edit', $value->id)}}">Edit</a>
                                            <a class="dropdown-item" onclick="deleteRecord('{{$value->id}}','Delete this State details?','Are you sure you want to delete this State details?');">Delete</a>
                                        </div>
                                    </td>

                                </tr>

                                @endforeach

                            </tbody>
                        </table>
                    </div>

                </form>
            </div>
        </div>
    </div>
    <!-- data table end -->
</div>

@section('js')
<script src="{{ asset('assets/admin/js/console/states.js') }}"></script>
@append

@endsection